export const USER_CONFIG = {
  // 👑 SUPER ADMIN - Full Access
  umair: {
    id: "umair",
    username: "umair",
    name: "Muhammad Umair",
    role: "super_admin",
    displayName: "👑 Umair (Admin)",
    accessLink: "https://my-production-dashboard.vercel.app/umair/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: true,
      editPlan: true,
      deletePlan: true,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: true,
      viewShortages: true,
      createShortage: true,
      editShortage: true,
      deleteShortage: true,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: true,
      editPriority: true,
      deletePriority: true,
      viewLiveNotes: true,
      createLiveNote: true,
      editLiveNote: true,
      deleteLiveNote: true,
      manageUsers: true,
      viewAuditLog: true,
    }
  },

  // 👑 ADMIN 2 - Haris
  haris: {
    id: "haris",
    username: "haris",
    name: "Haris",
    role: "super_admin",
    displayName: "👑 Haris (Admin)",
    accessLink: "https://my-production-dashboard.vercel.app/haris/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: true,
      editPlan: true,
      deletePlan: true,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: true,
      viewShortages: true,
      createShortage: true,
      editShortage: true,
      deleteShortage: true,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: true,
      editPriority: true,
      deletePriority: true,
      viewLiveNotes: true,
      createLiveNote: true,
      editLiveNote: true,
      deleteLiveNote: true,
      manageUsers: true,
      viewAuditLog: true,
    }
  },

  // 📋 PRODUCTION PLANNER - Shaveel
  shaveel: {
    id: "shaveel",
    username: "shaveel",
    name: "Shaveel",
    role: "production_planner",
    displayName: "📋 Shaveel (Planner)",
    accessLink: "https://my-production-dashboard.vercel.app/shaveel/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: true,
      editPlan: true,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: true,
      editShortage: true,
      deleteShortage: false,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: true,
      editPriority: true,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: true,
      editLiveNote: true,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 🏭 FLOOR SUPERVISOR - Rashid
  rashid: {
    id: "rashid",
    username: "rashid",
    name: "Rashid",
    role: "floor_supervisor",
    displayName: "🏭 Rashid (Supervisor)",
    shift: "morning",
    accessLink: "https://my-production-dashboard.vercel.app/rashid/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 🏭 SHORTAGE COMPLETE - Amir
  amir: {
    id: "amir",
    username: "amir",
    name: "Amir",
    role: "floor_supervisor",
    displayName: "🏭 Amir (Shortage Complete)",
    shift: "evening",
    accessLink: "https://my-production-dashboard.vercel.app/amir/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 🏭 SHORTAGE COMPLETE - Imran
  imran: {
    id: "imran",
    username: "imran",
    name: "Imran",
    role: "floor_supervisor",
    displayName: "🏭 Imran (Shortage Complete)",
    shift: "night",
    accessLink: "https://my-production-dashboard.vercel.app/imran/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 🏭 SHORTAGE COMPLETE - Riaz
  riaz: {
    id: "riaz",
    username: "riaz",
    name: "Riaz",
    role: "floor_supervisor",
    displayName: "🏭 Riaz (Shortage Complete)",
    shift: "morning",
    accessLink: "https://my-production-dashboard.vercel.app/riaz/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: true,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 📝 LIVE NOTES - Bilal Butt
  bilalbutt: {
    id: "bilalbutt",
    username: "bilalbutt",
    name: "Bilal Butt",
    role: "production_planner",
    displayName: "📝 Bilal Butt (Live Notes)",
    accessLink: "https://my-production-dashboard.vercel.app/bilalbutt/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: true,
      editDailyProduction: true,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: false,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: true,
      editLiveNote: true,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 👀 VIEWER - Waqar
  waqar: {
    id: "waqar",
    username: "waqar",
    name: "Waqar",
    role: "viewer",
    displayName: "👀 Waqar (Viewer)",
    accessLink: "https://my-production-dashboard.vercel.app/waqar/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: false,
      editDailyProduction: false,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: false,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 👀 VIEWER - Ali Akbar
  aliakbar: {
    id: "aliakbar",
    username: "aliakbar",
    name: "Ali Akbar",
    role: "viewer",
    displayName: "👀 Ali Akbar (Viewer)",
    accessLink: "https://my-production-dashboard.vercel.app/aliakbar/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: true,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: true,
      createDailyProduction: false,
      editDailyProduction: false,
      deleteDailyProduction: false,
      viewShortages: true,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: false,
      viewPriorities: true,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: true,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  },

  // 👀 VIEWER - Guest (Default)
  guest: {
    id: "guest",
    username: "guest",
    name: "Guest User",
    role: "viewer",
    displayName: "👀 Guest (Viewer)",
    accessLink: "https://my-production-dashboard.vercel.app/guest/dashboard",
    permissions: {
      viewDashboard: true,
      viewPlans: false,
      createPlan: false,
      editPlan: false,
      deletePlan: false,
      viewDailyProduction: false,
      createDailyProduction: false,
      editDailyProduction: false,
      deleteDailyProduction: false,
      viewShortages: false,
      createShortage: false,
      editShortage: false,
      deleteShortage: false,
      resolveShortage: false,
      viewPriorities: false,
      createPriority: false,
      editPriority: false,
      deletePriority: false,
      viewLiveNotes: false,
      createLiveNote: false,
      editLiveNote: false,
      deleteLiveNote: false,
      manageUsers: false,
      viewAuditLog: false,
    }
  }
};

export const getUserByUsername = (username) => {
  return USER_CONFIG[username] || USER_CONFIG.guest;
};

export const hasPermission = (username, permission) => {
  const user = getUserByUsername(username);
  return user?.permissions?.[permission] || false;
};

export const DEFAULT_USER = "umair";