// Guest user (Default Viewer)
guest: {
  id: "guest",
  username: "guest",
  name: "Guest User",
  role: "viewer",
  displayName: "👀 Guest (Viewer)",
  accessLink: "https://my-production-dashboard.vercel.app/guest/dashboard",
  permissions: {
    viewDashboard: true,
    viewPlans: false,        // ❌ Plans nahi dikhenge
    createPlan: false,
    editPlan: false,
    deletePlan: false,
    viewDailyProduction: false,
    createDailyProduction: false,
    editDailyProduction: false,
    deleteDailyProduction: false,
    viewShortages: false,
    createShortage: false,
    editShortage: false,
    deleteShortage: false,
    resolveShortage: false,
    viewPriorities: false,
    createPriority: false,
    editPriority: false,
    deletePriority: false,
    viewLiveNotes: false,
    createLiveNote: false,
    editLiveNote: false,
    deleteLiveNote: false,
    manageUsers: false,
    viewAuditLog: false,
  }
}